---
version: 2

project_name: fzf

before:
  hooks:
    - go mod download

builds:
  - binary: fzf
    targets:
      - linux_amd64_v2
      - linux_amd64_v4
      - darwin_amd64_v3
      - darwin_arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{ .RawVersion }}
      - -X main.revision={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}custom{{ end }}
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}-{{ .RawVersion }}-{{ .Os }}_{{ .Arch }}{{ if .Amd64 }}_{{ .Amd64 }}{{ end }}"
    formats:
      - tar.xz
    wrap_in_directory: true
    files:
      - bin/fzf-tmux
      - plugin/fzf.vim

snapshot:
  version_template: "{{ .Version }}-devel"

checksum:
  disable: true

changelog:
  disable: true
