---
project_name: fzf

before:
  hooks:
    - go mod download

builds:
  - binary: fzf
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - "-s -w -X main.version={{ .RawVersion }} -X main.revision={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}custom{{ end }}"

archives:
  - name_template: "{{ .ProjectName }}-{{ .RawVersion }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.xz
    files:
      - bin/fzf-tmux
      - plugin/fzf.vim

snapshot:
  name_template: "{{ .Tag }}-devel"

checksum:
  disable: true

changelog:
  skip: true
