---
project_name: fzf

before:
  hooks:
    - go mod download

builds:
  - binary: fzf
    targets:
      - linux_amd64_v4
      - darwin_amd64_v3
      - darwin_arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{ .RawVersion }}
      - -X main.revision={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}custom{{ end }}

archives:
  - name_template: '{{ .ProjectName }}-{{ .RawVersion }}-{{ .Os }}_{{ .Arch }}'
    format: tar.xz
    wrap_in_directory: true
    rlcp: true
    files:
      - bin/fzf-tmux
      - plugin/fzf.vim

snapshot:
  name_template: '{{ .Tag }}-devel'

checksum:
  disable: true

changelog:
  skip: true
